# License: MIT
# Copyright © 2026 Frequenz Energy-as-a-Service GmbH

---

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "part:tooling"
      - "type:tech-debt"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "part:tooling"
      - "type:tech-debt"
